name: 'Terraform CD'

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Download tfplan from previous workflow
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ./terraform
        run-id: ${{ github.event.workflow_run.id }}

    - name: Terraform Apply
      run: terraform apply tfplan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}